import tkinter

import sqlite3
con = sqlite3.connect('hotel.db')
cur =con.cursor()
#cur.execute('CREATE TABLE PunjabiHotel( CustomerId INTEGER,TabelId INTEGER,TotalBill INTEGER,Date STRING)')
#When the file is run once comment out the code that creates table
con.commit()

class HotelManagementGUI:
    
    def exit1(self):
       
        self.parent.destroy()
           
    def reset(self):
        self.roti.set("0")
        self.butterroti.set("0")
        self.naan.set("0")
        self.butternaan.set("0")
        self.s1.set("0")
        self.s2.set("0")
        self.s3.set("0")
        self.s4.set("0")
        self.s5.set("0")
        self.s6.set("0")
        self.s7.set("0")
        self.s8.set("0")
        self.d1.set("0")
        self.d2.set("0")
        self.d3.set("0")
        self.d4.set("0")
        self.d5.set("0")
        self.total_bill.set("0")
    def total(self):
        self.b1 = float(self.roti.get())
        self.b2 = float(self.butterroti.get())
        self.b3 = float(self.naan.get())
        self.b4 = float(self.butternaan.get())
        self.sc1 = float(self.s1.get())
        self.sc2 = float(self.s2.get())
        self.sc3 = float(self.s3.get())
        self.sc4 = float(self.s4.get())
        self.sc5 = float(self.s5.get())
        self.sc6 = float(self.s6.get())
        self.sc7 = float(self.s7.get())
        self.sc8 = float(self.s8.get())
        self.dc1 = float(self.d1.get())
        self.dc2= float(self.d2.get())
        self.dc3 = float(self.d3.get())
        self.dc4 = float(self.d4.get())
        self.dc5 = float(self.d5.get())
        self.bb1 = self.b1*40
        self.bb2 = self.b2*50
        self.bb3 = self.b3*40
        self.bb4 = self.b4*50
        self.sb1 = self.sc1*70
        self.sb2 = self.sc2*80
        self.sb3 = self.sc3*70
        self.sb4 = self.sc4*60
        self.sb5 = self.sc5*40
        self.sb6 = self.sc6*50
        self.sb7 = self.sc7*70
        self.sb8 = self.sc8*60
        self.db1 = self.dc1*60
        self.db2 = self.dc2*40
        self.db3 = self.dc3*50
        self.db4 = self.dc4*70
        self.db5 = self.dc5*70
        self.total_cost = self.bb1+self.bb2+self.bb3+self.bb4+self.sb1+self.sb2+self.sb3+self.sb4+self.sb5+self.sb6+self.sb7+self.sb8+self.db1+self.db2+self.db3+self.db4+self.db5
        self.total_bill.set("Rs."+str(self.total_cost))
    def create(self):
        con = sqlite3.connect('hotel.db')
        cur =con.cursor()
        cur.execute('INSERT INTO PunjabiHotel VALUES(?,?,?,?)',(self.customerIdEntry.get(),self.tabelIdEntry.get(),self.totalcostEntry.get(),self.dateEntry.get()))
        
        con.commit()
        cur.execute('SELECT * FROM PunjabiHotel')
        print(cur.fetchall())
        con.close()
    def menu(self):
        con = sqlite3.connect('hotel.db')
        cur =con.cursor()
        cur.execute('SELECT * FROM PunjabiHotel')
        self.records = cur.fetchall()
        
        for self.record in self.records:
            self.print_rec += str(self.record[0]) + "\n "+str(self.record[2])
        con.commit()
        con.close()
    def __init__(self,parent):
        self.parent = parent
        self.print_rec = ''
        self.roti = tkinter.StringVar()
        self.roti.set("0")
        self.butterroti = tkinter.StringVar()
        self.butterroti.set("0")
        self.naan = tkinter.StringVar()
        self.naan.set("0")
        self.s1 = tkinter.StringVar()
        self.s2 = tkinter.StringVar()
        self.s3 = tkinter.StringVar()
        self.s4 = tkinter.StringVar()
        self.s5 = tkinter.StringVar()
        self.s6 = tkinter.StringVar()
        self.s7 = tkinter.StringVar()
        self.s8 = tkinter.StringVar()
        self.d1 = tkinter.StringVar()
        self.d2 = tkinter.StringVar()
        self.d3 = tkinter.StringVar()
        self.d4 = tkinter.StringVar()
        self.d5 = tkinter.StringVar()
        self.date = tkinter.StringVar()
        self.butternaan = tkinter.StringVar()
        self.butternaan.set("0")
        self.customerID = tkinter.StringVar()
        self.tabelID = tkinter.StringVar()
        self.s1.set("0")
        self.s2.set("0")
        self.s3.set("0")
        self.s4.set("0")
        self.s5.set("0")
        self.s6.set("0")
        self.s7.set("0")
        self.s8.set("0")
        self.d1.set("0")
        self.d2.set("0")
        self.d3.set("0")
        self.d4.set("0")
        self.d5.set("0")
        self.date.set("")
        self.total_bill = tkinter.StringVar()
        self.total_bill.set("Rs.0")
        self.titleframe = tkinter.Frame(parent,relief = "ridge",bd = 10)
        self.titleframe.pack()
        self.menuframe = tkinter.Frame(parent,relief = "ridge",bd = 10,bg = "purple")
        self.menuframe.pack(side = "left",fill = "both")
        self.titlelabel = tkinter.Label(self.titleframe,text = "Punjabi Dhaba",bg = "purple",fg = "white",font = ("Calibri",30,"bold"),width = 30)
        self.titlelabel.grid(row = 0, column = 0)
        self.food = tkinter.Label(self.menuframe,text = "***Bread***",bg = "purple",fg = "white",font = ("Calibri",20,"bold"),width = 20)
        self.food.grid(row = 1,column = 0)
        self.food = tkinter.Label(self.menuframe,text = "Roti ---> Rs.40",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 2,column = 0)
        self.entry_roti = tkinter.Entry(self.menuframe,textvariable = self.roti,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_roti.grid(row = 2,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Butter Roti ---> Rs.50",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 3,column = 0)
        self.entry_butterroti = tkinter.Entry(self.menuframe,textvariable = self.butterroti,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_butterroti.grid(row = 3,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Naan ---> Rs.40",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 4,column = 0)
        self.entry_naan = tkinter.Entry(self.menuframe,textvariable = self.naan,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_naan.grid(row = 4,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Butter Naan ---> Rs.50",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 5,column = 0)
        self.entry_butternaan = tkinter.Entry(self.menuframe,textvariable = self.butternaan,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_butternaan.grid(row = 5,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "***Sabji and Rice***",bg = "purple",fg = "white",font = ("Calibri",20,"bold"),width = 20)
        self.food.grid(row = 6,column = 0)
        self.food = tkinter.Label(self.menuframe,text = "Paneer Tikka ---> Rs.70",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 7,column = 0)
        self.entry_s1 = tkinter.Entry(self.menuframe,textvariable = self.s1,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s1.grid(row = 7,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Paneer Butter ---> Rs.80",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 8,column = 0)
        self.entry_s2 = tkinter.Entry(self.menuframe,textvariable = self.s2,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s2.grid(row = 8,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Veg Kadhai ---> Rs.70",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 9,column = 0)
        self.entry_s3 = tkinter.Entry(self.menuframe,textvariable = self.s3,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s3.grid(row = 9,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Veg Tawa ---> Rs.60",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 10,column = 0)
        self.entry_s4 = tkinter.Entry(self.menuframe,textvariable = self.s4,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s4.grid(row = 10,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Plain Rice ---> Rs.40",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 11,column = 0)
        self.entry_s5 = tkinter.Entry(self.menuframe,textvariable = self.s5,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s5.grid(row = 11,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Jeera Rice ---> Rs.50",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 12,column = 0)
        self.entry_s6 = tkinter.Entry(self.menuframe,textvariable = self.s6,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s6.grid(row = 12,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Fried Rice ---> Rs.70",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 13,column = 0)
        self.entry_s7 = tkinter.Entry(self.menuframe,textvariable = self.s7,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s7.grid(row = 13,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Dal Tadka ---> Rs.60",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 14,column = 0)
        self.entry_s8 = tkinter.Entry(self.menuframe,textvariable = self.s8,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_s8.grid(row = 14,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "***Dessert***",bg = "purple",fg = "white",font = ("Calibri",20,"bold"),width = 20)
        self.food.grid(row = 15,column = 0)
        
        self.food = tkinter.Label(self.menuframe,text = "Chocolate ---> Rs.60",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 17,column = 0)
        self.entry_d1 = tkinter.Entry(self.menuframe,textvariable = self.d1,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_d1.grid(row = 17,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Vanilla ---> Rs.40",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 18,column = 0)
        self.entry_d2 = tkinter.Entry(self.menuframe,textvariable = self.d2,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_d2.grid(row = 18,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "ButterScotch ---> Rs.50",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 19,column = 0)
        self.entry_d3 = tkinter.Entry(self.menuframe,textvariable = self.d3,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_d3.grid(row = 19,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Mocktail ---> Rs.70",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 20,column = 0)
        self.entry_d4 = tkinter.Entry(self.menuframe,textvariable = self.d4,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_d4.grid(row = 20,column = 1)
        self.food = tkinter.Label(self.menuframe,text = "Brownie ---> Rs.70",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 20)
        self.food.grid(row = 21,column = 0)
        self.entry_d5 = tkinter.Entry(self.menuframe,textvariable = self.d5,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 10)
        self.entry_d5.grid(row = 21,column = 1)
        self.idframe = tkinter.Frame(parent,relief = "ridge",bd = 10,bg = "purple",width = 15)
        self.idframe.pack(side = "top")
        self.customerId = tkinter.Label(self.idframe,text = "Customer Id: ",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 15,)
        self.customerId.grid(row = 0,column = 0)
        self.customerIdEntry = tkinter.Entry(self.idframe,textvariable = self.customerID,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 15)
        self.customerIdEntry.grid(row = 0,column = 1)
        self.tabelId = tkinter.Label(self.idframe,text = "Table No: ",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 15,)
        self.tabelId.grid(row = 1,column = 0)
        self.tabelIdEntry = tkinter.Entry(self.idframe,bg = "#F8FAFF",textvariable = self.tabelID,fg = "black",font = ("Calibri",15),width = 15)
        self.tabelIdEntry.grid(row = 1,column = 1)
        self.timeframe = tkinter.Frame(parent,relief = "ridge",bd = 10,bg = "purple",width = 15)
        self.timeframe.pack(pady = 10,side = "top")
        self.date = tkinter.Label(self.timeframe,text = "Date: ",bg = "#E8DAEF",fg = "black",font = ("Calibri",15),width = 15,)
        self.date.grid(row = 0,column = 0)
        self.dateEntry = tkinter.Entry(self.timeframe,textvariable = self.date,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 15)
        self.dateEntry.grid(row = 0,column = 1)
        
       
        self.totalcostframe = tkinter.Frame(parent,relief = "ridge",bd = 10,bg = "purple",width = 15)
        self.totalcostframe.pack(pady = 10)
        self.button = tkinter.Button(self.totalcostframe,text = "Total Bill",font = "calibri 14",height = 2,width = 8,bg="#E8DAEF",fg="black",command = self.total)
        self.button.grid(row = 1,column = 0)
        self.totalcostEntry = tkinter.Entry(self.totalcostframe,textvariable = self.total_bill,bg = "#F8FAFF",fg = "black",font = ("Calibri",15),width = 15)
        self.totalcostEntry.grid(row = 1,column = 1)
        self.resetframe = tkinter.Frame(parent,relief = "ridge",bd = 10,bg = "purple",width = 15)
        self.resetframe.pack()
        self.button = tkinter.Button(self.resetframe,text = "Reset",font = "calibri 14",height = 2,width = 8,bg="#E8DAEF",fg="black",command = self.reset)
        self.button.grid(row = 2,column = 0)
        self.button = tkinter.Button(self.resetframe,text = "Close",font = "calibri 14",height = 2,width = 8,bg="#E8DAEF",fg="black",command = self.exit1)
        self.button.grid(row = 2,column = 1)
        self.submitframe = tkinter.Frame(parent,relief = "ridge",bd = 10,bg = "purple",width = 15)
        self.submitframe.pack()
        self.button1 = tkinter.Button(self.submitframe,text = "Submit",font = "calibri 14",height = 2,width = 8,bg="#E8DAEF",fg="black",command = self.create)
        self.button1.grid(row = 1,column = 0)
        
if __name__ == '__main__':
    window = tkinter.Tk()
    myapp = HotelManagementGUI(window)
    window.title('Hotel Management')
    window.geometry("760x740")
    window.config()
    window.mainloop()